### ISSUE TITLE
Do we want the agents to be chosen at random?

### ISSUE THREAD

**Issue by ils246** [ils246/SCM#5]
So do we want the agents to be chosen at random, or do we want to go in order every time we do one round at each tick?

**Comment by crisjf** [comment]
I vote for random, what do you think?

**Comment by ils246** [comment]
I understand why random would be desirable, but now that I am generating an array and then just following that order this should matter less. 

I am trying to make it as fast as I can to be able to run more of the large-N sims. 

I'm content with my progress but I still think we might end up running large Ns for only 4000 ticks (model converges at around 1000 to 2000 ) and only 50 repetitions for parameter setting. Any thoughts on this?

**Comment by crisjf** [comment]
If they are not chosen at random, then we should randomize the order at every tick. Do you think this will be faster?

**Comment by ils246** [comment]
probably not, because we still have to initialize the random number generator. I think the way in which I re-wrote it yesterday might be fast enough. The other thing we could do is for model 0, just have variables for q,p, and beta instead of an array. But this would probably change for model 1. 

I would have to test how much is the gain of doing it like this.

**Comment by crisjf** [comment]
That's a good idea, why don't you just rename the function we have from model0 to model1 and rewrite model0?

**Comment by ils246** [comment]
Yeah, I started to do that this morning but the other way around and then started to wonder if it was worth it. I'll get on it in a few.

**Comment by ils246** [comment]
Done, let me know if you find mistakes.
