### ISSUE TITLE
Fixed bug with talk function

### ISSUE THREAD

**Issue by ils246** [ils246/SCM#6]
I realized that the way the code was, the network topology was only used if the partner was = to the agent, because that was the only way in which it could enter the while loop under which you could choose the neighbors based on network topology. 

I fixed it, but please check to make sure I didn't make mistakes. 

For your reference, this was the code before m last commit:

`def talk(agent,memories,G=None):
    N=len(memories)
    partner = randint(0, N-1)
    while partner == agent:
        if G is None:
            partner = randint(0, N-1)
        else:
            neighs = G.neighbors(agent) #Change this line to upgrade to igraph
            if len(neighs)!=0:
                partner = choice(neighs)
            else:
                return memories
    partner = memories[partner]
    if len(partner) >  0:
        borrowedIdea = choice(list(partner))
        memories[agent].add(borrowedIdea)
    return memories
`

btw, that code snippet looks awful...

**Comment by crisjf** [comment]
Seems about right. Nice catch.

Does this affect any of the simulations you ran in Valparaiso?

**Comment by ils246** [comment]
I am currently running some simulations to see what are the effects. It shouldn't affect the sims on complete networks but it should have an effect on random / scale-free nets. 

Will give up an update once I'm done running things.
