### ISSUE TITLE
model1 needs to be tested

### ISSUE THREAD

**Issue by crisjf** [ils246/SCM#7]
It seems that model1 (under models.py) performs very similar to model0. It might make sense to drop model0 and just keep the code for model1, but we need to test it first.

**Comment by ils246** [comment]
I think the problem is that you are running model1 with a homogenous population. 

If `[100,100*[0.5],100*[0.1],100*[0.1],'complete']` are your parameters, every agent has the same p, q and beta. In model 1, what we want to do is have a heterogeneous population. 

You might want to specify different values for the params and test again.

**Comment by crisjf** [comment]
What I meant is that if you can run model1 with a homogenous population and get the same results as model0 in about the same time, why do we have two models?

**Comment by ils246** [comment]
I see what you mean. Yet, I can see two arguments for why we would need 2 models: 

1) If you ran tests for smaller populations, then the run times were probably very similar. As N grows, run times start to diverge more significantly.  Similarly, if you test with just  1000 time steps, then there isn't much difference. So far we have been running sims with T=20000. I ran the following tests: 

N=1000, T = 20000
Model 0 : 47.5057110786438 seconds
Model 1 :  53.477417945861816

N=2000, T= 20000
Model 0: 97.06999015808105 seconds
Model 1: 108.80456113815308 seconds

2) The way in which model 1 works now, we would be assigning different values of p to nodes independent of their degree. If we want to assign a higher p to hubs, then I can see why we would want to have two separate models. 

However, I am not particularly attached to the idea of having two models. If you really want to have just one model, then I wouldn't mind considering just having one.

**Comment by crisjf** [comment]
Let's leave both of them for now
